#! /bin/bash
# Lab RES-HTTP
# task3
cd task1
docker build -t task4-1 .
cd ..

cd task2
docker build -t task4-2 .
cd ..

cd task3
docker build -t task4-3 .
cd ..

docker run -d --name apache_static task4-1
docker run -d --name express_dynamic task4-2
docker run -d -p 7070:80 --name apache_rp task4-3