#! /bin/bash
# Lab RES-HTTP
# task3
docker kill $(docker ps -aq)
docker rm $(docker ps -aq)

docker build -t task4-1 task1/
docker build -t task4-2 task2/
docker build -t task4-3 task3/

docker run -d --name apache_static task4-1
docker run -d --name express_dynamic task4-2
docker run -d -p 7070:80 --name apache_rp task4-3